src/apps/web/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import (home, somos, gracias,
                     contacto, servicios,
                     servicio_detalle, clientes,
                     cliente_detalle, testimonios)

app_name = 'web'

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^somos/$', somos, name='somos'),
    url(r'^gracias/$', gracias, name='gracias'),
    url(r'^contacto/$', contacto, name='contacto'),
    url(r'^somos/$', somos, name='somos'),
    url(r'^testimonios/$', testimonios, name='testimonios'),
    url(r'^servicios/$', servicios, name='servicios'),
    url(r'^servicio/(?P<slug>[\w-]+)/$', servicio_detalle, name='servicio_detalle'),
    url(r'^clientes/$', clientes, name='clientes'),
    url(r'^cliente/(?P<slug>[\w-]+)/$', cliente_detalle, name='cliente_detalle'),
]

src/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from filebrowser.sites import site
from ckeditor_uploader import urls as ck_urls
from apps.web import urls as web_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^ckeditor/', include(ck_urls)),
    url(r'', include(web_urls, namespace='web')),
    # url(r'^localeurl/', include('localeurl.urls')),

    # url(r'', include(web_urls, namespace='web')),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
     static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))


handler404 = 'apps.web.views.page_404'
handler500 = 'apps.web.views.page_500'

src/templates/common/_base.html
<!DOCTYPE html>
{% load static seo%}
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" >

    {%metatags%}

    <!-- inicio favicon  iphone retina, ipad, iphone en orden-->
    <link rel="icon" type="image/png" href="{% static '' %}img/favicon/256.png"/>
    <link rel="apple-touch-icon-precomposed" sizes="180x180" href="{% static '' %}img/favicon/180.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static '' %}img/favicon/114.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static '' %}img/favicon/72.png">
    <link rel="apple-touch-icon-precomposed" href="{% static '' %}img/favicon/57.png">
    <!-- end favicon -->

    {% block cssadicional %}
    {% endblock %}

    <link rel="stylesheet" type="text/css" href="{% static '' %}css/styles.css?v=1{{ BUILD_ID }}"/>
<!-- 
    <link rel="stylesheet" type="text/css" href="{% static '' %}css/blocks_styl.css?v=2{{ BUILD_ID }}"/> -->

    <!--[if lt IE 9]>
        <script src="{% static '' %}js/html5.js"></script>
        <script src="{% static '' %}js/respond.js" type="text/javascript"></script>
        <link rel="stylesheet" type="text/css" href="{% static '' %}css/ie.css"/>
    <![endif]-->

</head>

<body class="{% block classbody %}{% endblock %}">

    <!-- html solo para el menu responsive -->
    <div  class="menu-mobile-open icon-menu"></div>
    <div class="menu-mobile-close icon-close"></div>
    <div class="menu-overlay"></div>
    <!-- html solo para el menu responsive -->

    <div class="cnt-wrapper">
        <div class="wrapper">
            <!-- HEADER START -->
            {% include "common/_header.html" %}
            <!-- HEADER END -->

            <!-- CONTENT START -->
            {% block content %}{% endblock %}
            <!-- CONTENT END -->
        </div>
    </div>

    <!-- FOOTER START -->
    {% include "common/_footer.html" %}
    <!-- FOOTER END -->

    <!-- contenedor del menu responsive -->
    <div class="menu-sidebar">
        <div class="menu-sidebar-cnt"></div>
    </div>

    <script src="{% static '' %}js/jquery1.8.3.min.js" type="text/javascript"></script>
    <script src="{% static '' %}js/main.min.js" type="text/javascript"></script>

    <!-- JSADD START -->
    {% block jsfinal %}{% endblock %}
    <!-- JSADD END -->

    <script type="text/javascript">
    </script>
    {% include 'common/_google_analytics.html' %}
</body>
</html>

src/templates/common/_base2.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" >
	<title></title>


	{% block cssadicional %}

	{% endblock %}
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/styles.css?v=2{{ BUILD_ID }}"/>
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/blocks_styl.css?v=2{{ BUILD_ID }}"/>
	
</head>

<body class="{% block classbody %}{% endblock %}">

			{% block content %}
			{% endblock %}

	<script src="{{ STATIC_URL }}js/jquery1.8.3.min.js" type="text/javascript"></script>
	<script src="{{ STATIC_URL }}js/jquery.placeholder.js" type="text/javascript"></script>
	<script src="{{ STATIC_URL }}js/main.js" type="text/javascript"></script>
	{% block jsfinal %}
	{% endblock %}

	<script type="text/javascript">

	</script>
</body>
</html>

src/templates/common/_base3.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" >
	<title></title>


	{% block cssadicional %}

	{% endblock %}
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/styles.css?v=2{{ BUILD_ID }}"/>
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/blocks_styl.css?v=2{{ BUILD_ID }}"/>
</head>

<body class="{% block classbody %}{% endblock %}">

			{% block content %}
			{% endblock %}

	<script src="{{ STATIC_URL }}js/jquery1.8.3.min.js" type="text/javascript"></script>
	<script src="{{ STATIC_URL }}js/mg/jquery.clipboard.js" type="text/javascript"></script>
	<script src="{{ STATIC_URL }}js/mg/general.js" type="text/javascript"></script>
	{% block jsfinal %}
	{% endblock %}

	<script type="text/javascript">

	</script>
</body>
</html>

src/templates/common/_footer.html
{% load static core_tags%}
<footer class="footer">
    <div class="wancho">
        <ul class="footer-wrapper">
            <li class="footer-list">
                <figure class="f-figure">
                    <img src="{% static '' %}img/120x35-2x.png" alt="" width="120" height="35">
                </figure>
            </li>

            <li class="footer-list">
                <i class="icon-mail-black-envelope-symbol"></i>
                <p>
                    {% for c in correos %}
                        <a href="mailto:{{c.email}}">{{c.email}}</a>
                    {% endfor %}
                </p>
            </li>

            <li class="footer-list f-tel">
                <i class="icon-phone-receiver"></i>
                <p>
                    {% for t in telefonos %}
                        <a href="tel:{{t.telefono|tel}}">{{t.telefono}}</a>{% if not forloop.last %}/{% endif %} 

                    {% endfor %}
                </p>
            </li>

            <li class="footer-list f-redes">
            {% if info.facebook %}
                <a href="{{info.faceboook}}" target="_blank" class="face"><i class="icon-facebook-with-circle"></i></a>
            {% endif %}
            {% if info.twitter %}
                <a href="{{info.twitter}}" target="_blank" class="twi"><i class="icon-twitter-with-circle"></i></a>
            {% endif %}
            </li>
            
        </ul>
    </div>

    <!-- creditos -->
    <section class="footer-copy">
        <div class="wancho">
            <div class="footer-copy-left">
                <p>ingeres Todos los derechos reservados. </p>
            </div>
            <div class="footer-copy-right">
                <a class="link-staff" target="_blank" href="http://www.staffcreativa.pe/">Diseño y desarrollo staffcreativa</a>
            </div>
        </div>
    </section>
</footer>

src/templates/common/_google_analytics.html
{% if info.ga %}
<script>
 (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
 (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
 m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
 })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

 ga('create', '{{ info.ga }}', 'auto');

 ga('send', 'pageview');

</script>
{% endif %}

src/templates/common/_header.html
{% load static %}
<header class="header">
    <div class="wancho header-ctn">
        <div class="header-logo">
            <a href="{% url 'web:home' %}">
                <img src="{% static '' %}img/158x46-2x.png" alt="" width="158" height="46">
            </a>            
        </div>

        <nav class="menu">
            <div class="menu-wrap">
                <ul class="menu-list"> <!-- "menu-list" es usado para el menu responsive -->
                    <li class="menu-item"><a href="{% url 'web:somos' %}" class="menu-link {% if tab == 'SO' %}active{% endif %}">Somos</a></li>
                    <li class="menu-item"><a href="{% url 'web:servicios' %}" class="menu-link {% if tab == 'SE' %}active{% endif %}">Servicios</a></li>
                    <li class="menu-item"><a href="{% url 'web:clientes' %}" class="menu-link {% if tab == 'CLI' %}active{% endif %}">Clientes</a></li>
                    <li class="menu-item"><a href="{% url 'web:testimonios' %}" class="menu-link {% if tab == 'TES' %}active{% endif %}">Testimonios</a></li>
                    <li class="menu-item"><a href="{% url 'web:contacto' %}" class="menu-link {% if tab == 'CO' %}active{% endif %}">Contacto</a></li>
                </ul>
            </div>
        </nav>

    </div>
</header>